# Generated by Django 4.1 on 2022-09-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=100)),
                ('Brend', models.CharField(db_index=True, max_length=150)),
                ('type', models.CharField(db_index=True, max_length=150)),
                ('razmer', models.CharField(db_index=True, max_length=150)),
                ('material', models.CharField(db_index=True, max_length=150)),
                ('sostav', models.TextField(blank=True, max_length=1000)),
                ('strana', models.CharField(db_index=True, max_length=150)),
                ('pol', models.CharField(choices=[('Man', 'Man'), ('Women', 'Women')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uploaded', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Characteristics',
                'verbose_name_plural': 'Characteristics',
            },
        ),
    ]
