# Generated by Django 4.1 on 2022-09-12 15:31

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0004_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='сharacteristics',
            name='Brend',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='сharacteristics',
            name='Sex',
            field=models.CharField(choices=[('Man', 'Мужской'), ('Women', 'Женский'), ('Child', 'Ребёнок')], max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='сharacteristics',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=[('#FFFFFF', 'white'), ('#000000', 'black')]),
        ),
        migrations.AlterField(
            model_name='сharacteristics',
            name='material',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='сharacteristics',
            name='razmer',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='сharacteristics',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='сharacteristics',
            name='sostav',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='сharacteristics',
            name='strana',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Страна Производитель'),
        ),
    ]
