# Generated by Django 4.1.1 on 2022-09-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0004_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(db_index=True, max_length=150, verbose_name='Цвет')),
                ('brand', models.CharField(db_index=True, max_length=150, verbose_name='Бренд')),
                ('type', models.CharField(db_index=True, max_length=150, verbose_name='Тип')),
                ('size', models.CharField(db_index=True, max_length=150, verbose_name='Размер')),
                ('material', models.CharField(db_index=True, max_length=150, verbose_name='Материал')),
                ('consist', models.TextField(blank=True, max_length=1000, verbose_name='Состав')),
                ('country', models.CharField(db_index=True, max_length=150, verbose_name='Страна Производитель')),
                ('sex', models.CharField(choices=[('Man', 'Мужской'), ('Women', 'Женский'), ('Child', 'Ребёнок')], max_length=10, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Характеристики',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.DeleteModel(
            name='Сharacteristics',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=20, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='category',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product/%Y'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.ManyToManyField(to='ecomm.characteristics'),
        ),
    ]
