# Generated by Django 4.0.7 on 2022-09-12 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0005_alter_category_slug_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='сharacteristics',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecomm.product'),
            preserve_default=False,
        ),
    ]
