# Generated by Django 4.0.7 on 2022-09-12 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0006_сharacteristics_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сharacteristics',
            new_name='Characteristics',
        ),
    ]
