# Generated by Django 4.0.7 on 2022-09-12 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0007_rename_сharacteristics_characteristics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characteristics',
            old_name='name',
            new_name='prod_name',
        ),
    ]
