# Generated by Django 4.1.1 on 2022-10-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="email",
        ),
        migrations.AddField(
            model_name="order",
            name="phone_number",
            field=models.CharField(default=0, max_length=13),
            preserve_default=False,
        ),
    ]
